<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [190]:
import pandas as pd

column_names = [ 'x1', 'x2', 'x3', 'y']
data = [
    [ 0, 0, 1, 0 ],
    [ 0, 1, 1, 1 ],
    [ 1, 0, 1, 1 ],
    [ 0, 1, 0, 1 ],
    [ 1, 0, 0, 1 ],
    [ 1, 1, 1, 0 ],
    [ 0, 0, 0, 0 ]]

df = pd.DataFrame(data, columns=column_names)

X = np.array(df[['x1', 'x2', 'x3']])
X
y = df['y'].values.reshape(-1,1)
y

array([[0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0]])

In [203]:
class XOR_Neural_Network(object):
    import numpy as np
    
    def __init__(self, niter=1000):        
        #Define Hyperparameters
        self.inputLayerSize = 3
        self.hiddenLayerSize = 4
        self.outputLayerSize = 1
        
        # Number of iterations
        self.niter = niter
        
        #Weights (parameters)
        self.weights1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize) # from inputs to first (only) hidden layer
        self.weights2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize) # from hidden layer to next (output) layer
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        sx = self.sigmoid(s)
        return sx * (1 - sx)
    
    def feed_forward(self, X):
        """Calculate inference using feed forward."""
        
        # Weighted Sum
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activate
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weighted sum of activated hidden (which output layer will use)
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final Activation of Output (My Predictions)
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        """Propagate backward through the network.
        X is the inputs.
        y is the TRUE values.
        o is the predicted OUTPUT values."""
        
        # Calculate the difference between 
#         print(y)
#         print('--------------------')
#         return
#         print("y\n")
#         print(y)
#         print("\n")
        
#         print("y.type\n")
#         print(type(y))
#         print("\n")
        
#         print("o\n")
#         print(o)
#         print("\n")
        
#         print("o type\n")
#         print(type(o))
#         print("\n")
        
#         print("y.T\n")
#         print(y.T)
#         print("\n")
        
#         print("y.T shape\n")
#         print(y.T.shape)
#         print("\n")
        

        self.o_error = y - o # Error in the output
#         print("self.o_error")
#         print(self.o_error)
#         return
    
        # Apply derivative of sigmoid to error
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error: how much were our output layer weights off
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        # z2 delta: how much were the weights off?
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
    
    
    def train(self, X,y):
        for _ in range(self.niter):
            o = self.feed_forward(X)
#             print(o)
            self.backward(X,y,o)
    
    def predict(self, X):
        """Return class label after unit step"""

        return list(map((lambda r: self.feed_forward(r) ), X))
            
p = XOR_Neural_Network()
p
p.train(X,y)
p.weights1

array([[ 8.02676276, -7.68053052,  2.42373356, -0.62095716],
       [-7.79853818,  9.18096629,  1.19724144,  1.319494  ],
       [ 1.4096968 ,  0.04833429, -0.01755879,  0.1474666 ]])

In [204]:
p.predict(X)

[array([0.00122126]),
 array([0.94742989]),
 array([0.94589196]),
 array([0.95024484]),
 array([0.94646449]),
 array([0.0895573]),
 array([0.05920216])]

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. 

You'll notice that each observation is a 28x28 arrary which represents an image. 

Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. 

We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [1]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

/home/gt/anaconda3/envs/U4-S1-NLP-DS10/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/gt/anaconda3/envs/U4-S1-NLP-DS10/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/gt/anaconda3/envs/U4-S1-NLP-DS10/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/gt/anaconda3/envs/U4-S1-NLP-

In [205]:
# input image dimensions
img_rows, img_cols = 28, 28

In [206]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [207]:
x_train.shape

(60000, 28, 28)

In [208]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [209]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [210]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [211]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [ ]:
##### Your Code Here #####



## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?